# Importing Lib 

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# importing the data

In [3]:
data=pd.read_csv("C:\\Users\\91976\\Downloads\\DATA SCI BATCH\\Dataset\\data_cleaned.csv")

In [4]:
data.head()

Survived   Age     Fare  Pclass_1  Pclass_2  Pclass_3  Sex_female  \
0         0  22.0   7.2500         0         0         1           0   
1         1  38.0  71.2833         1         0         0           1   
2         1  26.0   7.9250         0         0         1           1   
3         1  35.0  53.1000         1         0         0           1   
4         0  35.0   8.0500         0         0         1           0   

   Sex_male  SibSp_0  SibSp_1  ...  Parch_0  Parch_1  Parch_2  Parch_3  \
0         1        0        1  ...        1        0        0        0   
1         0        0        1  ...        1        0        0        0   
2         0        1        0  ...        1        0        0        0   
3         0        0        1  ...        1        0        0        0   
4         1        1        0  ...        1        0        0        0   

   Parch_4  Parch_5  Parch_6  Embarked_C  Embarked_Q  Embarked_S  
0        0        0        0           0           0           1  
1        0        0        0           1           0           0  
2        0        0        0           0           0           1  
3        0        0        0           0           0           1  
4        0        0        0           0           0           1  

[5 rows x 25 columns]

# separating variables: IV and DV

In [36]:
x=data.drop(["Survived"],axis=1)

In [37]:
x

Age     Fare  Pclass_1  Pclass_2  Pclass_3  Sex_female  Sex_male  \
0    22.000000   7.2500         0         0         1           0         1   
1    38.000000  71.2833         1         0         0           1         0   
2    26.000000   7.9250         0         0         1           1         0   
3    35.000000  53.1000         1         0         0           1         0   
4    35.000000   8.0500         0         0         1           0         1   
..         ...      ...       ...       ...       ...         ...       ...   
886  27.000000  13.0000         0         1         0           0         1   
887  19.000000  30.0000         1         0         0           1         0   
888  29.699118  23.4500         0         0         1           1         0   
889  26.000000  30.0000         1         0         0           0         1   
890  32.000000   7.7500         0         0         1           0         1   

     SibSp_0  SibSp_1  SibSp_2  ...  Parch_0  Parch_1  Parch_2  Parch_3  \
0          0        1        0  ...        1        0        0        0   
1          0        1        0  ...        1        0        0        0   
2          1        0        0  ...        1        0        0        0   
3          0        1        0  ...        1        0        0        0   
4          1        0        0  ...        1        0        0        0   
..       ...      ...      ...  ...      ...      ...      ...      ...   
886        1        0        0  ...        1        0        0        0   
887        1        0        0  ...        1        0        0        0   
888        0        1        0  ...        0        0        1        0   
889        1        0        0  ...        1        0        0        0   
890        1        0        0  ...        1        0        0        0   

     Parch_4  Parch_5  Parch_6  Embarked_C  Embarked_Q  Embarked_S  
0          0        0        0           0           0           1  
1          0        0        0           1           0           0  
2          0        0        0           0           0           1  
3          0        0        0           0           0           1  
4          0        0        0           0           0           1  
..       ...      ...      ...         ...         ...         ...  
886        0        0        0           0           0           1  
887        0        0        0           0           0           1  
888        0        0        0           0           0           1  
889        0        0        0           1           0           0  
890        0        0        0           0           1           0  

[891 rows x 24 columns]

In [7]:
y=data["Survived"]

In [8]:
y

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [9]:
x.shape

(891, 24)

In [10]:
y.shape

(891,)

# splitiing the data into train set and test set

In [11]:
from sklearn.model_selection import train_test_split

In [43]:
x_train,x_test, y_train, y_test = train_test_split(x_scale,y,test_size=0.30,random_state=56) 

In [44]:
x_train

array([[0.17064589, 0.2342244 , 1.        , ..., 0.        , 0.        ,
        1.        ],
       [0.22090978, 0.14346245, 0.        , ..., 0.        , 0.        ,
        1.        ],
       [0.78637849, 0.01871355, 0.        , ..., 0.        , 0.        ,
        1.        ],
       ...,
       [0.34656949, 0.02469116, 0.        , ..., 0.        , 0.        ,
        1.        ],
       [0.30887158, 0.17777476, 1.        , ..., 1.        , 0.        ,
        0.        ],
       [0.19577783, 0.07690368, 1.        , ..., 0.        , 0.        ,
        1.        ]])

In [45]:
x_test

array([[0.39683338, 0.14346245, 0.        , ..., 0.        , 0.        ,
        1.        ],
       [0.35913546, 0.12999454, 1.        , ..., 0.        , 0.        ,
        1.        ],
       [0.36792055, 0.01411046, 0.        , ..., 1.        , 0.        ,
        0.        ],
       ...,
       [0.77381252, 0.05182215, 1.        , ..., 0.        , 0.        ,
        1.        ],
       [0.18321186, 0.01410226, 0.        , ..., 1.        , 0.        ,
        0.        ],
       [0.59788892, 0.14976542, 1.        , ..., 1.        , 0.        ,
        0.        ]])

# Normalising using min_max_scaler

In [38]:
from sklearn.preprocessing import MinMaxScaler

In [39]:
scaler=MinMaxScaler()

In [40]:
columns=x_train.columns

In [16]:
columns

Index(['Age', 'Fare', 'Pclass_1', 'Pclass_2', 'Pclass_3', 'Sex_female',
       'Sex_male', 'SibSp_0', 'SibSp_1', 'SibSp_2', 'SibSp_3', 'SibSp_4',
       'SibSp_5', 'SibSp_8', 'Parch_0', 'Parch_1', 'Parch_2', 'Parch_3',
       'Parch_4', 'Parch_5', 'Parch_6', 'Embarked_C', 'Embarked_Q',
       'Embarked_S'],
      dtype='object')

In [41]:
x_scale=scaler.fit_transform(x)

In [42]:
x_scale

array([[0.27117366, 0.01415106, 0.        , ..., 0.        , 0.        ,
        1.        ],
       [0.4722292 , 0.13913574, 1.        , ..., 1.        , 0.        ,
        0.        ],
       [0.32143755, 0.01546857, 0.        , ..., 0.        , 0.        ,
        1.        ],
       ...,
       [0.36792055, 0.04577135, 0.        , ..., 0.        , 0.        ,
        1.        ],
       [0.32143755, 0.0585561 , 1.        , ..., 1.        , 0.        ,
        0.        ],
       [0.39683338, 0.01512699, 0.        , ..., 0.        , 1.        ,
        0.        ]])

In [24]:
x_train_scale=pd.DataFrame(x_train_scale, columns=columns)

In [25]:
x_train_scale

Age      Fare  Pclass_1  Pclass_2  Pclass_3  Sex_female  Sex_male  \
0    0.170646  0.234224       1.0       0.0       0.0         1.0       0.0   
1    0.220910  0.143462       0.0       1.0       0.0         0.0       1.0   
2    0.786378  0.018714       0.0       0.0       1.0         1.0       0.0   
3    0.246042  0.007832       0.0       0.0       1.0         0.0       1.0   
4    0.384267  0.321798       1.0       0.0       0.0         1.0       0.0   
..        ...       ...       ...       ...       ...         ...       ...   
618  0.371701  0.025374       0.0       1.0       0.0         0.0       1.0   
619  0.233476  0.015330       0.0       0.0       1.0         1.0       0.0   
620  0.346569  0.024691       0.0       1.0       0.0         1.0       0.0   
621  0.308872  0.177775       1.0       0.0       0.0         0.0       1.0   
622  0.195778  0.076904       1.0       0.0       0.0         1.0       0.0   

     SibSp_0  SibSp_1  SibSp_2  ...  Parch_0  Parch_1  Parch_2  Parch_3  \
0        0.0      1.0      0.0  ...      0.0      0.0      1.0      0.0   
1        1.0      0.0      0.0  ...      1.0      0.0      0.0      0.0   
2        1.0      0.0      0.0  ...      1.0      0.0      0.0      0.0   
3        1.0      0.0      0.0  ...      1.0      0.0      0.0      0.0   
4        1.0      0.0      0.0  ...      0.0      0.0      1.0      0.0   
..       ...      ...      ...  ...      ...      ...      ...      ...   
618      1.0      0.0      0.0  ...      1.0      0.0      0.0      0.0   
619      0.0      1.0      0.0  ...      1.0      0.0      0.0      0.0   
620      1.0      0.0      0.0  ...      1.0      0.0      0.0      0.0   
621      0.0      1.0      0.0  ...      1.0      0.0      0.0      0.0   
622      1.0      0.0      0.0  ...      0.0      1.0      0.0      0.0   

     Parch_4  Parch_5  Parch_6  Embarked_C  Embarked_Q  Embarked_S  
0        0.0      0.0      0.0         0.0         0.0         1.0  
1        0.0      0.0      0.0         0.0         0.0         1.0  
2        0.0      0.0      0.0         0.0         0.0         1.0  
3        0.0      0.0      0.0         1.0         0.0         0.0  
4        0.0      0.0      0.0         0.0         0.0         1.0  
..       ...      ...      ...         ...         ...         ...  
618      0.0      0.0      0.0         0.0         0.0         1.0  
619      0.0      0.0      0.0         0.0         0.0         1.0  
620      0.0      0.0      0.0         0.0         0.0         1.0  
621      0.0      0.0      0.0         1.0         0.0         0.0  
622      0.0      0.0      0.0         0.0         0.0         1.0  

[623 rows x 24 columns]

# modeling

In [26]:
from sklearn.linear_model import LogisticRegression

In [27]:
from sklearn.metrics import f1_score,accuracy_score,confusion_matrix,roc_auc_score,roc_curve

In [31]:
LG=LogisticRegression(random_state=123,max_iter=200)

# creating instance of logestic regression 

In [46]:
# fitting the model

LG.fit(x_train,y_train)

LogisticRegression(max_iter=200, random_state=123)

In [47]:
LG.coef_

array([[-1.79539035,  0.57656604,  0.96278715,  0.07958127, -1.04269176,
         1.10629823, -1.10662158,  0.92271138,  0.99836131,  0.51432934,
        -0.52889313, -0.80519694, -0.45758213, -0.64405318,  0.07339233,
         0.75603215,  0.17055681,  0.26184902, -0.63515489, -0.28316087,
        -0.34383791,  0.19123391,  0.18939812, -0.38095538]])

In [48]:
LG.intercept_

array([-0.07793331])

# Prediction

In [70]:
y_pred=LG.predict(x_test)

In [71]:
y_pred

array([0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 1], dtype=int64)

In [72]:
f1_score(y_pred,y_test)

0.7597765363128491

In [69]:
y_predict

array([[0.82170802, 0.        ],
       [0.52518053, 0.        ],
       [0.84453091, 0.        ],
       [0.2468475 , 1.        ],
       [0.41837444, 0.        ],
       [0.15428902, 1.        ],
       [0.90581721, 0.        ],
       [0.88543337, 0.        ],
       [0.96323412, 0.        ],
       [0.89639147, 0.        ],
       [0.06795366, 1.        ],
       [0.63932367, 0.        ],
       [0.11850372, 1.        ],
       [0.4976795 , 0.        ],
       [0.93176262, 0.        ],
       [0.8876451 , 0.        ],
       [0.06380142, 1.        ],
       [0.37297358, 1.        ],
       [0.92860658, 0.        ],
       [0.09711218, 1.        ],
       [0.51266734, 0.        ],
       [0.7333677 , 0.        ],
       [0.82527123, 0.        ],
       [0.03949941, 1.        ],
       [0.67085376, 0.        ],
       [0.89647984, 0.        ],
       [0.37297358, 1.        ],
       [0.22745976, 1.        ],
       [0.06717545, 1.        ],
       [0.02725512, 1.        ],
       [0.

In [52]:
y_predict=LG.predict_proba(x_test)

In [53]:
y_predict

array([[0.82170802, 0.17829198],
       [0.52518053, 0.47481947],
       [0.84453091, 0.15546909],
       [0.2468475 , 0.7531525 ],
       [0.41837444, 0.58162556],
       [0.15428902, 0.84571098],
       [0.90581721, 0.09418279],
       [0.88543337, 0.11456663],
       [0.96323412, 0.03676588],
       [0.89639147, 0.10360853],
       [0.06795366, 0.93204634],
       [0.63932367, 0.36067633],
       [0.11850372, 0.88149628],
       [0.4976795 , 0.5023205 ],
       [0.93176262, 0.06823738],
       [0.8876451 , 0.1123549 ],
       [0.06380142, 0.93619858],
       [0.37297358, 0.62702642],
       [0.92860658, 0.07139342],
       [0.09711218, 0.90288782],
       [0.51266734, 0.48733266],
       [0.7333677 , 0.2666323 ],
       [0.82527123, 0.17472877],
       [0.03949941, 0.96050059],
       [0.67085376, 0.32914624],
       [0.89647984, 0.10352016],
       [0.37297358, 0.62702642],
       [0.22745976, 0.77254024],
       [0.06717545, 0.93282455],
       [0.02725512, 0.97274488],
       [0.

In [54]:
y_predict_encoded=y_predict[:,1]

In [55]:
y_predict_encoded

array([0.17829198, 0.47481947, 0.15546909, 0.7531525 , 0.58162556,
       0.84571098, 0.09418279, 0.11456663, 0.03676588, 0.10360853,
       0.93204634, 0.36067633, 0.88149628, 0.5023205 , 0.06823738,
       0.1123549 , 0.93619858, 0.62702642, 0.07139342, 0.90288782,
       0.48733266, 0.2666323 , 0.17472877, 0.96050059, 0.32914624,
       0.10352016, 0.62702642, 0.77254024, 0.93282455, 0.97274488,
       0.50850644, 0.1240259 , 0.10663106, 0.63669809, 0.66789873,
       0.14603363, 0.62516556, 0.22658755, 0.90938313, 0.11083467,
       0.76954437, 0.1176411 , 0.43906755, 0.50251834, 0.09552002,
       0.22966737, 0.09418279, 0.48018127, 0.15546847, 0.08800474,
       0.2418535 , 0.13492704, 0.24041853, 0.68290506, 0.09418279,
       0.11005419, 0.11228384, 0.08807326, 0.10467714, 0.11008222,
       0.17966246, 0.2627315 , 0.16990183, 0.6126392 , 0.07612712,
       0.42554318, 0.15556761, 0.62700229, 0.15671463, 0.78660693,
       0.09418279, 0.79589823, 0.04104115, 0.91791393, 0.80818

In [63]:
for i in range(0, len(y_predict_encoded)):
    if (y_predict_encoded[i]>0.7):
        y_predict_encoded[i]=1
        
    else:
        y_predict_encoded[i]=0

In [64]:
y_predict_encoded

array([0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1.,
       1., 0., 1., 0., 0., 0., 1., 0., 0., 1., 1., 1., 1., 0., 0., 0., 1.,
       1., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1.,
       0., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 1., 1., 1., 0., 1., 0.,
       0., 1., 0., 1., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 1., 0., 0., 1.,
       0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 1., 1., 1., 0.,
       0., 0., 0., 0., 0.

In [65]:
f1_score(y_predict_encoded,y_test)

0.6871165644171779

In [66]:
accuracy_score(y_predict_encoded,y_test)

0.8097014925373134

In [73]:
accuracy_score(y_pred,y_test)

0.8395522388059702